### ISSUE TITLE
Small typo in code Line::setup

### ISSUE THREAD

**Issue by ahmedmetin** [mattEhall/MoorDyn#1]
Hi, 
There is a small mistake in Line::setup. I think you forgot to multiply with one more d when calculating volume. I don't think it causes any problem, but still. :)
for (int i=0; i<N; i++)	
	{	l[i] = UnstrLen/double(N);	// distribute line length evenly over segments
		V[i] = l[i]*0.25*pi*d;
	}

**Comment by mattEhall** [comment]
Thanks for noting this! I've corrected it in the latest commit, ea5ccf8c050f359cdd13a0a8b6f5cc5f3158405c.
