### ISSUE TITLE
MoorDyn V2 docs sample inputfile

### ISSUE THREAD

**Issue by evamschmitt** [mattEhall/MoorDyn#11]
Hi,

Of course MoorDyn V2 is still under development, but could you provide a working sample inputfile in the docs?

Many thanks!!

**Comment by mattEhall** [comment]
Yes, there are the test examples here (https://github.com/mattEhall/MoorDyn/tree/dev/test/Mooring) and I will make a point to include a full example input file (in addition to the existing piecemeal example) in the documentation when we update it.
