### ISSUE TITLE
Matlab Moordyn Code: Error: unable to open lines.txt file and Error: dtC is less than dtM.  (0.5 < 0)

### ISSUE THREAD

**Issue by alekboving** [mattEhall/MoorDyn#24]
Hello,
I am trying to write a simple matlab code for moordyn. I have gotten the matlab code to work and the moordyn initiated console shows up. But everytime it opens I am left with two errors: Error: unable to open lines.txt file and Error: dtC is less than dtM.  (0.5 < 0). Could someone help me resolve these issues? All my files are included in the moordyn.zip seen below.
[moordyn.zip](https://github.com/mattEhall/MoorDyn/files/8382942/moordyn.zip)

**Comment by timmaflan** [comment]
Hello Alek,
Were you able to sort out this issue? I am having the same error appear. I am currently running moordyn through WEC-Sim, and matlab crashes fully after these two errors appear. 
Thanks!

**Comment by luop21** [comment]
I meet the same problem? anyone knows how to solve it?

**Comment by luop21** [comment]
Error:dtC is less than dtM. 

I want to couple Star and MoorDyn, But I met proble above!

**Comment by sanguinariojoe** [comment]
Hey loup!

Please, do not necrobump closed issues.

This issue is closed because MoorDyn v2 has now a nice Matlab wrapper. See
the documentation here:

https://moordyn.readthedocs.io/en/latest/drivers.html#matlab

If your issue is not Matlab related, please feel free to open a new issue
