### ISSUE TITLE
Issue with applying steady force at nodes (vessel)

### ISSUE THREAD

**Issue by hamzaJayy** [mattEhall/MoorDyn#29]
Dear Mat, 

I am trying to model high frequency vibration of mooring connector when vessel (farilead) is provided pre-described motion (picture shown below)

![image](https://user-images.githubusercontent.com/106804145/178430656-65547f5e-8dcd-4949-b522-1b1b0b073b60.png)

I am applying constant force at fairlead(vessel) in postive z-direction to create tension in the mooring line. I am attaching the mooring input file and my matlab code below.

[lines.txt](https://github.com/mattEhall/MoorDyn/files/9090462/lines.txt)

%%%%%%%%%
clc
clear 
close all
% add mooring lines input-file folder into path
addpath Mooring\
%% Setup
tic;
amp = 0.1; % m
freq = 0.0254; % Hz
time = 2*1/freq; % time of simulation
dt = (freq)/2; % coupling time step size (time between MoorDyn calls)
N = round(time/dt); % number of coupling time steps
Ts = zeros(N+1,1); % time step array
X = zeros(N+1,3); % platform  position
X(1,1) = 0; % platform initial position
XD = [0,0,0]; % platform initial velocity
FairTens1 = zeros(N,1); % array for storing fairlead 1 tension time series
FLines = zeros(N,6);
FLines_temp = zeros(1,6); % going to make a pointer so LinesCalc can modify FLines
FLines_p = libpointer('doublePtr',FLines_temp); % access returned value with FLines_p.value
%% Initialization
loadlibrary('Lines.dll','MoorDyn.h'); % load MoorDyn DLL
calllib('Lines','LinesInit',X(1,:),XD) % initialize MoorDyn
%% Simulation
XD(1,1) = amp*freq*2*pi*cos(2*pi*freq*Ts(1));
for i=1:N

p=calllib('Lines', 'LinesCalc', X(i,:), XD(i,:), FLines_p, Ts(i), dt); % some MoorDyn time stepping
Ts(i+1) = dt*i; % store time
X(i+1,1) = amp*sin(2*pi*freq*Ts(i+1));
XD(i+1,1) = amp*freq*2*pi*cos(2*pi*freq*Ts(i+1));
end

%% Ending
calllib('Lines','LinesClose'); % close MoorDyn
unloadlibrary Lines; % unload library (never forget to do this!)
Tend = toc;
%%

close all
var = readtable('Lines.out','FileType','delimitedtext');
%%%%%%%

Issues I am having:

1) when force is applied at vessel node thorugh moorDyn input file, the force/tensions only appears when FairTen is calculated. The tenions in mooring line segments does not appear. As result, the morring line does not get the pre-tension, which is desire to study the natural frequncy of mooring line when under tension

2) The units wriiten in force sectioon for force is kN in moorDyn input file. But the results shows moorDyn reads input file forces in N. 

3) I am facing issues in convergence and dynamic relaxation. Sometime, when I run the simulation, it shows error: Nan occurred. If I run it again, without changing anything, it runs fine. I am not sure where is the issue. 

One general question: I am trying to model cable dynamics/ taut cable dynamics to study the natural frequency of the mooring line. I am trying to study given the dimension of mooring connector, how it is going impact mooring line. As a senior,, what is suggestion regarding the suitability of MoorDyn to the analysis I am interested in. 

Thank you. Your response will be a great help. Please do let me know if I need to provide some extra information to help you understand the issues I am facing.

**Comment by mattEhall** [comment]
Hi, here are some quick answers:
1. It looks like the top Connection is "vessel" type, which means its motion is entirely prescribed. As a result, you can't pull on it with a vertical force to affect the pretension of a line attached to it. (If the point can't move, it can't stretch a mooring line to create a change in tension.) You'll need to figure out a different way to get the pretension you want. Shortening the line length to achieve the required strain in the mooring line would do it.
2. It looks like the (kN) is a typo in the input file and it should be (N).
3. Unfortunately MoorDyn has had a mysterious problem when run from Matlab where after the first run it behaves incorrectly (and unpredictably) until Matlab is restarted. Probably only your first result is correct. For avoiding NaNs, it is a matter of having a small enough time step and large enough size and mass of line segments. It is tricky to model very short and light lines.

Some adjustments are needed, but I think MoorDyn should work for what you're trying to investigate!
Matt

**Comment by hamzaJayy** [comment]
Thanks Matt for your response. Following your suggestions, I am able to resolve the issues I was facing
