### ISSUE TITLE
Intel support

### ISSUE THREAD

**Issue by hfchen18** [mattEhall/MoorDyn#6]
I compiled MoorDyn with Intel 19.1.1 and got pointer errors. Could you provide a makefile for Intel compiler?

**Comment by mattEhall** [comment]
Hi, sorry, I don't have a makefile for the Intel compiler and it's not a task I'd be able to take on for you. If you want to share the errors you're seeing, maybe I or someone else could offer some ideas.

**Comment by hfchen18** [comment]
Thanks very much for your reply, Matt. I will try using gcc compiler instead.
