### ISSUE TITLE
Error in vq_mag calculation

### ISSUE THREAD

**Issue by imestevez** [mattEhall/MoorDyn#8]
I think the following line in the code
https://github.com/mattEhall/MoorDyn/blob/ea5ccf8c050f359cdd13a0a8b6f5cc5f3158405c/Line.cpp#L644

should be: double vq_mag = sqrt(vq_squared);

**Comment by sanguinariojoe** [comment]
Fixed [here](https://github.com/mattEhall/MoorDyn/pull/12/commits/b2d8a20fd6578449a89585e0196683e86e85b09e). Please @mattEhall close this
